// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoABF7QLUvWiiNZ8aq_25Q47HMCYJicYY',
    appId: '1:607938131075:web:b5b27555061ada6340d7b6',
    messagingSenderId: '607938131075',
    projectId: 'practice-project-33c22',
    authDomain: 'practice-project-33c22.firebaseapp.com',
    storageBucket: 'practice-project-33c22.appspot.com',
    measurementId: 'G-SWCPE0CEEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBB8qzdRGHrCfx_uGXj0NYLYZJIdoKZ-E',
    appId: '1:607938131075:android:6789d6b2934f7dfd40d7b6',
    messagingSenderId: '607938131075',
    projectId: 'practice-project-33c22',
    storageBucket: 'practice-project-33c22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAks6wy3J6s9l2XZ_Qvbjnd6d4F5gfq7Wc',
    appId: '1:607938131075:ios:dfe9cd51f264827140d7b6',
    messagingSenderId: '607938131075',
    projectId: 'practice-project-33c22',
    storageBucket: 'practice-project-33c22.appspot.com',
    iosBundleId: 'com.example.flutterNotificationsWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAks6wy3J6s9l2XZ_Qvbjnd6d4F5gfq7Wc',
    appId: '1:607938131075:ios:24edcebe9dd67d2040d7b6',
    messagingSenderId: '607938131075',
    projectId: 'practice-project-33c22',
    storageBucket: 'practice-project-33c22.appspot.com',
    iosBundleId: 'com.example.flutterNotificationsWithFirebase.RunnerTests',
  );
}
